#!/usr/bin/env bash

# This script is designed to be run either locally by the developer, or as part
# of a Github action.

set -eou pipefail

./bootstrap
./configure
make all
if ! make check; then
    test -f test/test-suite.log && cat test/test-suite.log
    exit 1
fi
make distcheck
